# Version
version: '3.1'

# Setup
services:
  # PHP
  php:
    depends_on:
      - db
    image: docker-php-dev
    restart: always
    ports:
      - 5080:80
    volumes:
      - ./development:/var/www/html
  
  # PHPMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 5081:80
    environment:
      PMA_HOST: db
  
  # MySQL
  db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    volumes:
      - wordpress_db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  
# Volumes
volumes:
  wordpress_db:
  wordpress_uploads: