# Version
version: '3.1'

# Setup
services:
  # PHP
  php:
    depends_on:
      - mysql
    image: docker-php-dev
    restart: always
    ports:
      - 80:80
    volumes:
      - ./development:/var/www/html
    networks:
      - bridge
  
  # MySQL
  mysql:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    volumes:
      - database:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: db_dev
      MYSQL_USER: user_dev
      MYSQL_PASSWORD: pass_dev
      MYSQL_ROOT_PASSWORD: pass_dev
    networks:
      - bridge
  
# Volumes
volumes:
  database:

# Networks
networks:
  bridge:
    driver: bridge